#!/bin/sh

# This is a shell script whose job it is to update the
#  package version numbers before each commit is made

packages="mre_dmcts_core mre_dmcts_msgs mre_dmcts_nodes mre_dmcts_sim mre_dmcts_tests mre_dmcts mre_dmcts_mcplanner"

# Get number of commits in the history
revisioncount=$(git log --oneline | wc -l)

# Get name of most recent git tag (AKA code release version)
projectversion=$(git describe --tags --long | sed "s/v//")
cleanversion=${projectversion%%-*}
previoushash=$(git log -1 --pretty="%H")

fullversion="$cleanversion.$revisioncount"

for package in $packages; do
	fname="${package}/package.xml"
	echo "[pre-commit] Writing version number '$fullversion' to $fname."

	# Edit the getVersion function and update its return value with the new version string
	pattern="s/<version>.*<\/version>/<version>$fullversion<\/version>/"
	sed -i "$pattern" $fname
	
	# Add the file to the commit that is about to happen
	git add $fname
done
echo ""
