# DARPA SubT "urban" scenario

globalMap:
  scenarioName: "urban_full"
  resolution: 0.2   # [m]
  groundTruthImage: "$(find dmce_sim)/maps/urban_full.png"


robot:
  diameter: 0.5 # [m]
  speed: 1    # [m/s]
  map: # Parameters for the robot's local submap
    resolution: 0.25 # [m]
  startingArea:
    position_x: -23 # [m]
    position_y: 13  # [m]

mcts:
  randomDisplacement:
    length: 3 # [m] Size of the displacement
